language: python

python:
    - "3.4"

before_install:
    - apt-get -y install python2.7
    - apt-get -y install python-pip
    - apt-get -y install libxml2-dev
    - apt-get -y install libicu-dev
    - apt-get -y install python-pyicu

# command to install dependencies
install: 
    - pip install sqlalchemy codecov pytest-cov

# command to run tests
script: 
    - python --version
    - py.test
    - py.test --cov-report xml --cov=toy_nets tests/

after_success:
    - codecov
